/**
 * Stable identifiers for the failures a user can actually act on.
 *
 * The `message` on an error response is a developer-facing fallback: it is
 * written once, in one language, and cannot be localised after the fact. The
 * client matches on `code` instead and renders its own wording, which is what
 * lets the same API serve a Turkish and an English front-end.
 *
 * These strings are part of the API contract — renaming one silently changes
 * what a client displays, so treat them the way you would a route.
 */
export const ErrorCode = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_NO_SESSION: 'AUTH_NO_SESSION',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  ONBOARDING_ALREADY_COMPLETED: 'ONBOARDING_ALREADY_COMPLETED',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_USERNAME_TAKEN: 'USER_USERNAME_TAKEN',
  USER_CANNOT_DEACTIVATE_SELF: 'USER_CANNOT_DEACTIVATE_SELF',
  USER_LAST_ACTIVE_ADMINISTRATOR: 'USER_LAST_ACTIVE_ADMINISTRATOR',
  ROLE_PERMISSIONS_IMMUTABLE: 'ROLE_PERMISSIONS_IMMUTABLE',

  VILLA_NOT_FOUND: 'VILLA_NOT_FOUND',
  FLOOR_NOT_FOUND: 'FLOOR_NOT_FOUND',
  FLOOR_ENTIRE_VILLA_EXISTS: 'FLOOR_ENTIRE_VILLA_EXISTS',
  FLOOR_NOT_RENTABLE: 'FLOOR_NOT_RENTABLE',

  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',

  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  RESERVATION_CONFLICT: 'RESERVATION_CONFLICT',
  RESERVATION_INVALID_TRANSITION: 'RESERVATION_INVALID_TRANSITION',
  RESERVATION_STALE_WRITE: 'RESERVATION_STALE_WRITE',
  RESERVATION_INVALID_DATE_RANGE: 'RESERVATION_INVALID_DATE_RANGE',
  RESERVATION_GUEST_COUNT_EXCEEDS_CAPACITY: 'RESERVATION_GUEST_COUNT_EXCEEDS_CAPACITY',
  RESERVATION_DELETE_IN_STAY: 'RESERVATION_DELETE_IN_STAY',
  RESERVATION_DELETE_HAS_PAYMENTS: 'RESERVATION_DELETE_HAS_PAYMENTS',

  HOUSEKEEPING_TASK_NOT_FOUND: 'HOUSEKEEPING_TASK_NOT_FOUND',
  HOUSEKEEPING_INVALID_TRANSITION: 'HOUSEKEEPING_INVALID_TRANSITION',

  MAINTENANCE_RECORD_NOT_FOUND: 'MAINTENANCE_RECORD_NOT_FOUND',
  MAINTENANCE_INVALID_TRANSITION: 'MAINTENANCE_INVALID_TRANSITION',

  EXPENSE_NOT_FOUND: 'EXPENSE_NOT_FOUND',
  EXPENSE_VILLA_MISMATCH: 'EXPENSE_VILLA_MISMATCH',

  SETTINGS_LOGO_REQUIRED: 'SETTINGS_LOGO_REQUIRED',

  /** Raised by the database when the service-layer check was raced past. */
  CONSTRAINT_CONFLICT: 'CONSTRAINT_CONFLICT',
  CONSTRAINT_INVALID_VALUES: 'CONSTRAINT_INVALID_VALUES',
  RECORD_ALREADY_EXISTS: 'RECORD_ALREADY_EXISTS',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  RECORD_REFERENCE_MISSING: 'RECORD_REFERENCE_MISSING',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
